server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**,/orderStates/**
        - id: Delivery
          uri: http://localhost:8082
          predicates:
            - Path=/deliveries/** 
        - id: Check
          uri: http://localhost:8083
          predicates:
            - Path=/checks/** 
        - id: Product
          uri: http://localhost:8084
          predicates:
            - Path=/products/** 
        - id: Payment
          uri: http://localhost:8085
          predicates:
            - Path=/payments/** 
        - id: Notify
          uri: http://localhost:8086
          predicates:
            - Path= 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://Order:8080
          predicates:
            - Path=/orders/**,/orderStates/**
        - id: Delivery
          uri: http://Delivery:8080
          predicates:
            - Path=/deliveries/** 
        - id: Check
          uri: http://Check:8080
          predicates:
            - Path=/checks/** 
        - id: Product
          uri: http://Product:8080
          predicates:
            - Path=/products/** 
        - id: Payment
          uri: http://Payment:8080
          predicates:
            - Path=/payments/** 
        - id: Notify
          uri: http://Notify:8080
          predicates:
            - Path= 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
